import {NextResponse} from 'next/server';
import {z} from 'zod';
import {access} from '@/lib/access';
import {database,readPool,saveWeek} from '@/lib/storage';
import {weekSchema,sameOrigin} from '@/lib/validation';
import {players} from '@/lib/pool';
export async function GET(){try{const a=await access();if(!a.admin)return NextResponse.json({error:'Administrator access required.'},{status:403});const rows=await database().prepare('SELECT player,email FROM members ORDER BY player').all();return NextResponse.json({members:rows.results},{headers:{'Cache-Control':'no-store'}})}catch{return NextResponse.json({error:'Unable to load player access.'},{status:503})}}
export async function POST(request:Request){if(!sameOrigin(request))return NextResponse.json({error:'Request origin is not allowed.'},{status:403});try{const a=await access();if(!a.admin||!a.user)return NextResponse.json({error:'Administrator access required.'},{status:403});const b=await request.json() as {action?:string;week?:unknown;revision:number};
 if(b.action==='member'){const v=z.object({player:z.enum(players),email:z.string().email().max(254)}).safeParse(b);if(!v.success)return NextResponse.json({error:'Enter a valid player and email.'},{status:400});const email=v.data.email.trim().toLowerCase();const existing=await database().prepare('SELECT player FROM members WHERE email=? AND player<>?').bind(email,v.data.player).first();if(existing)return NextResponse.json({error:'That email is assigned to another player.'},{status:400});await database().prepare('INSERT INTO members (player,email,user_id) VALUES (?,?,NULL) ON CONFLICT(player) DO UPDATE SET email=excluded.email,user_id=CASE WHEN members.email=excluded.email THEN members.user_id ELSE NULL END').bind(v.data.player,email).run();return NextResponse.json({ok:true})}
 const v=weekSchema.safeParse(b.week);if(!v.success||!Number.isInteger(b.revision)||b.revision<0)return NextResponse.json({error:'Check the teams, results, amounts, and total points.'},{status:400});
 await readPool();if(!await saveWeek(v.data,b.revision,a.user.userId))return NextResponse.json({error:'Someone updated this week. Reload the latest data before saving.'},{status:409});return NextResponse.json({ok:true,revision:b.revision+1});
 }catch(e){console.error('Admin save failed',e);return NextResponse.json({error:'Could not save. Your entries are preserved; please retry.'},{status:503})}}
