import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {hashPassword, verifyPassword, sign, unsign} from '../lib/password.ts';
import {document, weekFromDocument, diff, apply, revision} from '../lib/changes.ts';
process.env.AUTH_SECRET = 'test-only-session-secret-with-at-least-32-characters';
const password = 'a sufficiently long test password';
const hashed = await hashPassword(password);
assert.equal(await verifyPassword(password, hashed), true);
assert.equal(await verifyPassword('incorrect password', hashed), false);
assert.equal(await verifyPassword(password, ''), false);
const signed = sign({id: 'player', exp: 123});
assert.deepEqual(unsign(signed), {id: 'player', exp: 123});
assert.equal(unsign(signed+'tampered'), null);
assert.equal(unsign('forged.payload'), null);
const base = JSON.parse(readFileSync(new URL('../lib/seed.json', import.meta.url))).weeks[2];
const kevin = structuredClone(base), mike = structuredClone(base);
kevin.games[0].picks.Kevin = kevin.games[0].teams[1];
mike.games[0].picks.Mike = mike.games[0].teams[0];
kevin.totalPoints.Kevin = 101;
mike.totalPoints.Mike = 102;
const doc = document(base);
apply(doc, diff(document(base), document(kevin)));
apply(doc, diff(document(base), document(mike)));
const merged = weekFromDocument(doc);
assert.equal(merged.totalPoints.Kevin, 101);
assert.equal(merged.totalPoints.Mike, 102);
assert.equal(merged.games[0].picks.Kevin, kevin.games[0].picks.Kevin);
assert.equal(merged.games[0].picks.Mike, mike.games[0].picks.Mike);
assert.notEqual(revision(base), revision(merged));
assert.deepEqual(weekFromDocument(document(base)), base);
assert.throws(() => apply({}, [{path: ['__proto__','polluted'], value: true}]));
console.log('PASS: password hashing, forged sessions, concurrent player saves, stable revisions, and unsafe change paths.');

const {sameOrigin} = await import('../lib/origin.ts');
process.env.NODE_ENV = 'production';
const publicUrl = 'https://cpfootballpool.netlify.app';
const req = (origin, extra = {}) => new Request('http://localhost:3000/api/auth', {headers: {...(origin ? {origin} : {}), ...extra}});
assert.equal(sameOrigin(req(publicUrl)), true);
assert.equal(sameOrigin(req('https://evil.example')), false);
assert.equal(sameOrigin(req('https://cpfootballpool.netlify.app.evil.example')), false);
assert.equal(sameOrigin(req('http://cpfootballpool.netlify.app')), false);
assert.equal(sameOrigin(req(null)), false);
assert.equal(sameOrigin(req('null')), false);
assert.equal(sameOrigin(req('https://evil.example', {'x-forwarded-host':'evil.example','x-forwarded-proto':'https'})), false);
process.env.NODE_ENV = 'development';
assert.equal(sameOrigin(req('http://localhost:3000')), true);
console.log('PASS: proxied production origins, hostile/missing origins, forwarded-header spoofing, and local development.');

const {validNewPassword}=await import('../lib/password-policy.ts');
for(const value of ['abcde','12345','!!!!!','Ab1!?'])assert.equal(validNewPassword(value),true);
for(const value of ['', 'abcd','abc d',' abcde','abcde ','abc\tde','abc\nde','abc\u00a0de'])assert.equal(validNewPassword(value),false);
assert.equal(validNewPassword('a'.repeat(129)),false);
const shortHash=await hashPassword('12345');assert.equal(await verifyPassword('12345',shortHash),true);
console.log('PASS: five-character passwords, no complexity requirement, whitespace rejection, and short-password authentication.');
