import assert from 'node:assert/strict';
import {csvCell, exportVisibleCsv} from '../lib/export-csv';
import {visiblePool} from '../lib/submissions';
import type {Pool} from '../lib/pool';
import seed from '../lib/seed.json';
assert.equal(csvCell('A, "B"\nC'), '"A, ""B""\nC"');
assert.equal(csvCell('=HYPERLINK("url")'), '"\'=HYPERLINK(""url"")"');
assert.equal(csvCell(0), '"0"');
assert.equal(csvCell(null), '""');
const pool=structuredClone(seed) as Pool;
const week=pool.weeks[2];
week.revealed=false;week.submitted={Bryan:false,Ed:false,Mike:false,Kevin:false};
week.games[0].picks.Bryan='SECRET_PICK';week.totalPoints.Bryan=123456;
week.games[0].picks.Kevin='MY_PICK';week.totalPoints.Kevin=0;
const csv=exportVisibleCsv(visiblePool(pool,'Kevin'));
assert.ok(csv.startsWith('\uFEFF"Week","Matchup","Bryan","Ed","Mike","Kevin","Winner","Score","Weekly Winner","Weekly Earnings"\r\n'));
assert.ok(!csv.includes('SECRET_PICK'));assert.ok(!csv.includes('123456'));
assert.ok(csv.includes('"MY_PICK"'));
assert.ok(csv.includes('"3","Total Points (last game)","Private","Private","Private","0"'));
assert.ok(csv.endsWith('\r\n'));
console.log('PASS: CSV headers, escaping, Excel formula protection, total-points rows, zeros, and private-pick redaction.');
