import {correct, players, standings, weeklyLeaders, type Pool} from './pool';
import {revealed, visiblePool} from './submissions';

const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const dollars = (n: number) => new Intl.NumberFormat('en-US', {style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
export function weeklyReport(pool: Pool, number: number, origin: string) {
 const source = pool.weeks.find(w => w.number === number);
 if (!source?.games.length) throw new Error('This week has no matchups yet.');
 if (!revealed(source)) throw new Error('Reports are available only after all four players have submitted and picks are revealed.');
 // Use only public, revealed weeks for every statistic in the newsletter.
 const view = visiblePool(pool, null), week = view.weeks.find(w => w.number === number)!;
 const season = {...view, weeks:view.weeks.filter(w => w.number <= number)};
 const ranks = standings(season), best = ranks[0].correct;
 const leaders = ranks.filter(p => p.correct === best).map(p => p.name).join(' & ');
 const results = week.games.filter(g => g.winner).length, complete = results === week.games.length;
 const calculated = weeklyLeaders(week);
 const winner = week.winner || (calculated.length === 1 ? calculated[0] : '');
 const winnerLabel = week.winner ? 'RECORDED WEEKLY WINNER' : winner ? 'CALCULATED WEEKLY WINNER' : 'WEEKLY WINNER';
 const headline = winner ? `${winner} takes the spotlight.` : complete ? 'Down to the wire.' : 'The week is still in play.';
 const winnerText = winner || (complete && calculated.length > 1 ? `Tied: ${calculated.join(' & ')}` : 'Still to be decided');
 const weekly = [...players].sort((a,b)=>correct(week,b)-correct(week,a));
 const pushes = week.games.filter(g=>g.winner==='Push').length;
 const solo = week.games.filter(g=>g.winner && g.winner!=='Push' && players.filter(p=>g.picks[p]===g.winner).length===1);
 const sweeps = week.games.filter(g=>g.winner && g.winner!=='Push' && players.every(p=>g.picks[p]===g.winner)).length;
 const photo = [{file:'namath.jpeg',width:300,alt:'Vintage black-and-white football photograph of a quarterback passing under pressure.'},{file:'butkus.jpeg',width:640,alt:'Vintage black-and-white football photograph of a tackle at the line.'},{file:'walker.jpeg',width:300,alt:'Vintage black-and-white football photograph of a runner leaping over defenders.'}][(number-1)%3];
 const link = `${new URL(origin).origin}/pool?tab=picks&week=${number}`;
 const browserLink = `${new URL(origin).origin}/newsletter/${number}`;
 const intro = winner ? `${winner} has the week's bragging rights${week.winner ? ` and ${dollars(week.earnings)} in recorded earnings` : '; the payout is awaiting the administrator'}. ${complete?'Every spread result is in.':`${results} of ${week.games.length} spread results are entered; the recorded winner is shown while the remaining results are pending.`}` : `${results} of ${week.games.length} spread results are entered. ${complete?'The tiebreaker still has a say.':'There is still football left on the board.'}`;
 const notes = [solo.length ? `${solo.length} lone-wolf call${solo.length===1?'':'s'}: ${solo.map(g=>`${players.find(p=>g.picks[p]===g.winner)} on ${g.winner}`).join('; ')}.` : 'No lone-wolf winners among the entered results.',`${sweeps} clean sweep${sweeps===1?'':'s'} for all four players. ${pushes} push${pushes===1?'':'es'} (zero points).`, 'Pick ’em. Talk trash. Come back next week.'];
 const subject = `Collins Phillips • Week ${number} ${complete?'results':'results update'} • ${winner?`${winner} wins`:'The race continues'}`;
 const td = 'padding:12px 9px;border-bottom:1px solid #ddd9cf;text-align:left;font:13px/1.5 Arial,sans-serif;color:#24392e;';
 const table = (headers:string[],rows:string[][]) => `<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;table-layout:fixed"><thead><tr>${headers.map(h=>`<th scope="col" style="${td}background:#183d2d;color:#fff;font-size:10px;text-transform:uppercase;word-wrap:break-word">${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td style="${td}word-wrap:break-word">${escape(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const section = (title:string,body:string) => `<tr><td style="padding:24px 24px 4px"><h2 style="margin:0 0 16px;font:700 24px Georgia,serif;color:#183d2d">${title}</h2>${body}</td></tr>`;
 const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(subject)}</title></head><body style="margin:0;background:#e9e7df;color:#24392e"><div style="display:none;max-height:0;overflow:hidden">${escape(intro)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#e9e7df"><tr><td align="center" style="padding:24px 8px"><table role="presentation" width="640" cellpadding="0" cellspacing="0" style="width:100%;max-width:640px;background:#faf8f1;border:1px solid #cbc8bb">
 <tr><td style="padding:14px 24px;text-align:center;font:14px Arial,sans-serif"><a href="${escape(browserLink)}" style="color:#183d2d">View newsletter in your browser</a></td></tr>
 <tr><td style="padding:27px 24px;background:#123b2c;color:#fff;border-bottom:5px solid #d8b65a"><p style="margin:0 0 12px;font:11px Arial,sans-serif;letter-spacing:3px;color:#e6d18d">COLLINS PHILLIPS FOOTBALL POOL • EST. 2023</p><h1 style="margin:0;font:700 43px/1 Georgia,serif">THE FINAL WHISTLE</h1><p style="margin:14px 0 0;font:12px Arial,sans-serif;color:#e0e5d6">${escape(pool.season)} / WEEK ${number} / ${complete?'WEEKLY RESULTS':'RESULTS IN PROGRESS'}</p></td></tr>
 <tr><td style="padding:22px 24px"><p style="margin:0 0 8px;color:#7b6124;font:700 11px Arial,sans-serif;letter-spacing:2px">${winnerLabel}</p><h2 style="margin:0 0 12px;font:700 34px/1.1 Georgia,serif;color:#183d2d">${escape(headline)}</h2><p style="font:15px/1.7 Arial,sans-serif;margin:0">${escape(intro)}</p><p style="font:700 16px Arial,sans-serif">${escape(winnerText)}</p>${week.note?`<p style="border-left:3px solid #d8b65a;padding-left:12px;font:13px/1.6 Arial,sans-serif"><b>Commissioner’s note:</b> ${escape(week.note)}</p>`:''}</td></tr>
 <tr><td align="center"><img src="${escape(new URL('/newsletter/'+photo.file,origin).href)}" width="${photo.width}" alt="${escape(photo.alt)}" style="display:block;width:100%;max-width:${photo.width}px;height:auto;border:0"><p style="margin:0;padding:8px 24px;font:10px Arial,sans-serif;color:#687365">FROM THE FOOTBALL SCRAPBOOK • Photo supplied by the pool administrator</p></td></tr>
 ${section('The weekly scoreboard',table(['Player','Correct picks','Total-points pick','Distance'],weekly.map(p=>[p,String(correct(week,p)),week.totalPoints[p]===null?'Not entered':String(week.totalPoints[p]),week.totalPoints[p]===null||week.actualTotal===null?'Pending':String(Math.abs(week.totalPoints[p]!-week.actualTotal))]))+`<p style="font:12px/1.6 Arial,sans-serif">Tiebreaker: last game listed. Actual total: <b>${week.actualTotal??'Pending'}</b>. Closest prediction wins a tie.</p>`)}
 ${section('The season chase',`<p style="font:14px/1.6 Arial,sans-serif"><b>${escape(leaders)}</b> ${leaders.includes('&')?'share the lead':'leads'} with ${best} correct picks through Week ${number}. Season champions are decided by weekly wins / earnings.</p>`+table(['Player','Correct picks','Weekly wins','Earnings'],ranks.map(p=>[p.name,String(p.correct),String(p.wins),dollars(p.earnings)])))}
 ${section('Under the lights',`<ul style="padding-left:20px;font:14px/1.7 Arial,sans-serif">${notes.map(n=>`<li>${escape(n)}</li>`).join('')}</ul>`)}
 ${section('Every game. Every call.',week.games.map((g,i)=>`<div style="padding:16px 0;border-bottom:1px solid #ddd9cf"><p style="margin:0 0 6px;font:700 15px/1.5 Arial,sans-serif">${String(i+1).padStart(2,'0')} / ${escape(g.matchup)}</p><p style="margin:0 0 8px;font:13px Arial,sans-serif;color:#466248">Spread result: <b>${escape(g.winner||'Pending')}</b> · Score: ${escape(g.score||'Not entered')}</p><p style="margin:0;font:12px/1.8 Arial,sans-serif">${players.map(p=>`${p}: ${escape(g.picks[p]||'No pick')}${g.winner&&g.winner!=='Push'&&g.picks[p]===g.winner?' ✓':''}`).join(' &nbsp; / &nbsp; ')}</p></div>`).join(''))}
 <tr><td style="padding:30px 24px"><a href="${escape(link)}" style="display:inline-block;padding:15px 20px;background:#183d2d;color:#fff;text-decoration:none;font:700 14px Arial,sans-serif">Back to the weekly picks →</a></td></tr><tr><td style="padding:20px 24px;background:#e5e6db;font:11px/1.7 Arial,sans-serif;color:#506046">Sent by your pool administrator to selected players. Results reflect saved pool data at the time of sending.<br>COLLINS PHILLIPS FOOTBALL POOL · EST. 2023</td></tr></table></td></tr></table></body></html>`;
 const text = [`COLLINS PHILLIPS FOOTBALL POOL — THE FINAL WHISTLE`,`${pool.season} • Week ${number}`,headline,intro,`View newsletter in your browser: ${browserLink}`,`Weekly winner: ${winnerText}`,week.note?`Commissioner’s note: ${week.note}`:'',`WEEKLY SCOREBOARD`,...weekly.map(p=>`${p}: ${correct(week,p)} correct; total points: ${week.totalPoints[p]??'Pending'}`),`Actual total: ${week.actualTotal??'Pending'}`,`SEASON THROUGH WEEK ${number}`, ...ranks.map(p=>`${p.name}: ${p.correct} correct, ${p.wins} weekly wins, ${dollars(p.earnings)}`),...notes,`GAME RESULTS`,...week.games.map(g=>`${g.matchup} — Spread result: ${g.winner||'Pending'}; Score: ${g.score||'Not entered'}. ${players.map(p=>`${p}: ${g.picks[p]||'No pick'}`).join('; ')}`),`Weekly picks: ${link}`].filter(Boolean).join('\n\n');
 return {subject,html,text,document:{
  season:pool.season,number,complete,headline,intro,winnerLabel,winnerText,note:week.note,photo:photo.file,link,
  weekly:weekly.map(p=>[p,String(correct(week,p)),String(week.totalPoints[p]??'Pending'),week.totalPoints[p]===null||week.actualTotal===null?'Pending':String(Math.abs(week.totalPoints[p]!-week.actualTotal))]),
  tiebreaker:`Last game listed. Actual total: ${week.actualTotal??'Pending'}. Closest prediction wins a tie.`,
  seasonIntro:`${leaders} ${leaders.includes('&')?'share the lead':'leads'} with ${best} correct picks through Week ${number}. Season champions are decided by weekly wins / earnings.`,
  standings:ranks.map(p=>[p.name,String(p.correct),String(p.wins),dollars(p.earnings)]),notes,
  games:week.games.map(g=>({matchup:g.matchup,result:`Spread result: ${g.winner||'Pending'} | Score: ${g.score||'Not entered'}`,picks:players.map(p=>`${p}: ${g.picks[p]||'No pick'}${g.winner&&g.winner!=='Push'&&g.picks[p]===g.winner?' (correct)':''}`).join(' / ')})),
 }};
}
