'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowDown,ArrowUp,Minus,Trophy,ClipboardCheck,Target,Flag,Pause,Play,ArrowRight} from 'lucide-react';
import HeroVideo from './hero-video';
import type {LandingData} from './model';
import './landing.css';
function Clock({deadline,initial,compact=false}:{deadline:number;initial:number;compact?:boolean}){
 const [seconds,setSeconds]=useState(initial);
 useEffect(()=>{const tick=()=>setSeconds(Math.max(0,Math.floor((deadline-Date.now())/1000)));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[deadline]);
 if(compact)return <span className="ticker-deadline">{seconds?`${Math.floor(seconds/86400)}D ${String(Math.floor(seconds/3600)%24).padStart(2,'0')}H ${String(Math.floor(seconds/60)%60).padStart(2,'0')}M TO LOCK`:'DEADLINE PASSED'}</span>;
 return <div className="game-clock" aria-label={seconds?`${Math.floor(seconds/86400)} days, ${Math.floor(seconds/3600)%24} hours until picks close`:'Pick deadline passed'}>{[Math.floor(seconds/86400),Math.floor(seconds/3600)%24,Math.floor(seconds/60)%60,seconds%60].map((v,i)=><div key={i}><strong>{String(v).padStart(2,'0')}</strong><span>{['DAYS','HRS','MIN','SEC'][i]}</span></div>)}</div>;
}
function Score({value,paused}:{value:number;paused:boolean}){
 const ref=useRef<HTMLSpanElement>(null);const [display,setDisplay]=useState(value);
 useEffect(()=>{if(paused||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame=0;const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)return;observer.disconnect();const start=performance.now();const tick=(now:number)=>{const progress=Math.min(1,(now-start)/650);setDisplay(Math.round(value*(1-Math.pow(1-progress,3))));if(progress<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick)},{threshold:1});if(ref.current)observer.observe(ref.current);return()=>{observer.disconnect();cancelAnimationFrame(frame)}},[value,paused]);
 return <span ref={ref}><span className="sr-only">{value}</span><span aria-hidden="true">{display}</span></span>;
}
export default function Landing({data:d}:{data:LandingData}){
 const [paused,setPaused]=useState(false);const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('entered');observer.unobserve(entry.target)}}),{threshold:.12});root.current?.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 const ticker=[`COLLINS PHILLIPS FOOTBALL POOL`,`WEEK ${String(d.week).padStart(2,'0')}`,`PICKS CLOSE WEDNESDAY`,`PICK LEADER: ${d.ranks[0].name.toUpperCase()}`, ...d.ranks.slice(0,3).map((p,i)=>`${i+1}. ${p.name.toUpperCase()} / ${p.correct} CORRECT`),d.latest.toUpperCase(),'UPSET FEED: NOT TRACKED'];
 return <div ref={root} className={`football-landing ${paused?'motion-paused':''}`}>
  <a className="landing-skip" href="#how-it-works">Skip to content</a>
  <section className="stadium-hero" aria-labelledby="landing-title">
   <HeroVideo paused={paused}/><div className="hero-shade"/><div className="hero-grain"/>
   <header className="landing-header"><a href="/" className="cp-monogram">CP<span>FOOTBALL POOL</span></a><nav aria-label="Main navigation"><a href="/pool">The pool</a><a href="/history">The history</a><a href="/signin" className="header-signin">Player sign in <ArrowUpRight size={15}/></a></nav></header>
   <div className="hero-copy"><div className="hero-kicker"><span/> FOUR PLAYERS. ONE TRADITION.</div><h1 id="landing-title">COLLINS PHILLIPS<br/><em>FOOTBALL</em><br/>POOL<span className="hero-period">.</span></h1><p className="hero-tagline">Pick ’em. Talk trash. Collect.</p><div className="hero-actions"><a className="stadium-button primary" href="/pool">Make your picks <ArrowUpRight size={21}/></a><a className="stadium-button secondary" href="/pool?tab=standings">View standings <ArrowRight size={18}/></a></div></div>
   <div className="heritage-crest" aria-label="Established 2023"><span>COLLINS • PHILLIPS</span><strong>CP</strong><small>EST. 2023</small><span>★ FOOTBALL POOL ★</span></div>
   <div className="hero-baseline"><span>{d.season} SEASON <b> / </b> WEEK {String(d.week).padStart(2,'0')}</span><span className="hero-caption">EVERY PICK HAS SOMETHING ON THE LINE.</span><button onClick={()=>setPaused(!paused)} aria-pressed={paused} aria-label={paused?'Play motion':'Pause motion'}>{paused?<Play size={14}/>:<Pause size={14}/>} {paused?'PLAY':'PAUSE'} MOTION</button></div>
  </section>
  <div className="broadcast" aria-label="Pool scoreboard"><div className="broadcast-label"><span/> POOL WIRE</div><Clock deadline={d.deadline} initial={d.seconds} compact/><div className="crawl-window" tabIndex={0} aria-label="Scoreboard updates. Focus to pause scrolling."><div className="crawl">{[0,1].map(copy=><div className="crawl-copy" key={copy} aria-hidden={copy===1?true:undefined}>{ticker.map((item,i)=><span key={i}>{item}<b>✦</b></span>)}</div>)}</div></div></div>
  <main className="landing-main">
   <section id="how-it-works" className="landing-section how-section"><div className="section-top" data-reveal><div><p className="landing-eyebrow">01 / THE PLAYBOOK</p><h2>SIMPLE GAME.<br/><span>SERIOUS BRAGGING RIGHTS.</span></h2></div><p>Four friends. A full slate.<br/>One winner every week.</p></div><div className="how-grid">{[{icon:ClipboardCheck,title:'MAKE THE CALL.',text:'Pick every matchup against the spread. Enter your total-points prediction for the last game.'},{icon:Target,title:'BEAT THE CLOCK.',text:'Submit by Wednesday. Picks stay private until all four players submit every pick and total points.'},{icon:Flag,title:'TAKE THE WEEK.',text:'Most correct picks wins. Tied? Closest to the final game’s total points takes it.'}].map((item,i)=><article className="play-card" data-reveal key={item.title}><div className="play-card-top"><item.icon size={30} strokeWidth={1.5}/><span>0{i+1}</span></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><p className="rule-footnote">Once everyone submits, picks are revealed and locked. Only the administrator can make corrections.</p></section>
   <section className="landing-section week-section" id="this-week"><div className="week-intro" data-reveal><p className="landing-eyebrow">02 / ON THE CLOCK</p><h2>WEEK <span>{String(d.week).padStart(2,'0')}.</span><br/>YOU’RE UP.</h2><p>Picks close Wednesday. Get your calls in before the clock runs out.</p><Clock deadline={d.deadline} initial={d.seconds}/><p className="clock-caption">{new Intl.DateTimeFormat('en-US',{weekday:'long',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/Chicago',timeZoneName:'short'}).format(d.deadline)}<br/>Already revealed? Player picks are locked.</p><a href="/pool" className="text-link">Open the week’s pick sheet <ArrowUpRight size={20}/></a></div><div className="matchup-board" data-reveal><div className="board-title"><span>THE WEEK’S SLATE</span><span>{d.gameCount} MATCHUPS</span></div>{d.matchups.map(m=><a href="/pool" key={m.number} className="matchup-preview"><span className="match-index">{String(m.number).padStart(2,'0')}</span><strong>MATCHUP {String(m.number).padStart(2,'0')}</strong><span>{m.spread===null?'SPREAD TBD':`${m.spread} PT SPREAD`}</span><ArrowUpRight size={16}/></a>)}<div className="board-note">Numbered preview · Full matchups in the pick sheet<br/>{d.fromAirtable?'Connected pool data':'Workbook snapshot · Live data unavailable'}</div></div></section>
   <section className="landing-section leaderboard-section"><div className="section-top" data-reveal><div><p className="landing-eyebrow">03 / THE CHASE</p><h2>TOP OF THE <span>PILE.</span></h2></div><a className="text-link" href="/pool?tab=standings">Full standings <ArrowUpRight size={20}/></a></div><p className="ranking-note">Current season · Ranked by correct picks, then earnings. Season titles are decided by weekly wins.</p><div className="landing-leaders">{d.ranks.slice(0,2).map((p,i)=><article data-reveal className={`landing-leader ${i===0?'first-place':''}`} key={p.name}><div className="leader-rank">0{i+1}</div><div className="leader-identity"><span>{i===0?'SETTING THE PACE':'IN THE HUNT'}</span><h3>{p.name}</h3><small>{p.movement>0?<ArrowUp size={13}/>:p.movement<0?<ArrowDown size={13}/>:<Minus size={13}/>} {p.movement?`${Math.abs(p.movement)} place${Math.abs(p.movement)>1?'s':''}`:'Holding position'} · {d.movementLabel.toLowerCase()}</small></div>{i===0&&<Trophy className="leader-trophy" size={44} strokeWidth={1.3}/>}<div className="leader-numbers"><div><strong><Score value={p.correct} paused={paused}/></strong><span>CORRECT</span></div><div><strong><Score value={p.wins} paused={paused}/></strong><span>WEEKLY WINS</span></div><div><strong>$<Score value={p.earnings} paused={paused}/></strong><span>EARNINGS</span></div></div></article>)}</div></section>
   <section className="landing-section champions-section"><div className="section-top" data-reveal><div><p className="landing-eyebrow">04 / IN THE RAFTERS</p><h2>SEASONS END.<br/><span>LEGENDS STAY.</span></h2></div><p>The names that earned their place.<br/>Champions by weekly wins.</p></div><div className="banner-row">{d.champions.map(c=><a data-reveal href="/history" className="championship-banner" key={c.year}><span className="banner-star">★</span><span className="banner-season">{c.year}</span><span className="banner-title">{c.shared?'CO-CHAMPIONS':'SEASON CHAMPION'}</span><h3>{c.names}</h3><div className="banner-rule"/><span>{c.wins} WEEKLY WINS</span><small>COLLINS PHILLIPS FOOTBALL POOL</small></a>)}</div><a href="/history" className="text-link">Explore the full history <ArrowUpRight size={20}/></a></section>
  </main>
  <footer className="landing-footer"><a href="/" className="footer-brand">COLLINS PHILLIPS<span>FOOTBALL POOL / EST. 2023</span></a><nav aria-label="Footer navigation"><a href="/pool">The pool</a><a href="/history">History</a><a href="#how-it-works">Rules</a><a href="mailto:kc6330119@gmail.com">Contact</a></nav><p>THE TRADITION CONTINUES.</p></footer>
 </div>;
}
