'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Week,Game,Player,players} from '@/lib/pool';
export function Choice({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value||'__blank'} onValueChange={v=>onChange(v==='__blank'?'':v)}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="__blank">Not entered</SelectItem>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
const opts=(a:readonly string[])=>a.map(s=>({value:s,label:s}));
export function PicksEditor({week,player,save}:{week:Week;player:Player;save:(w:Week,kind:'picks'|'week')=>Promise<void>}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(week),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <Dialog open={open} onOpenChange={v=>{if(busy)return;setOpen(v);if(v){setDraft(structuredClone(week));setError('')}}}><DialogTrigger asChild><button className="button primary">Enter my picks</button></DialogTrigger><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{player}’s Week {week.number} picks</DialogTitle><DialogDescription>Pick the team that covers the listed spread. Save before the Wednesday deadline.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await save(draft,'picks');setOpen(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="form-scroll">{draft.games.map(g=><label className="pick-edit" key={g.id}><span>{g.matchup}</span><Choice label={g.matchup} value={g.picks[player]} onChange={v=>setDraft({...draft,games:draft.games.map(x=>x.id===g.id?{...x,picks:{...x.picks,[player]:v}}:x)})} options={opts([...new Set([...g.teams,...(g.picks[player]&&!g.teams.includes(g.picks[player])?[g.picks[player]]:[])])])}/></label>)}<label className="field">Total points prediction<input type="number" min="0" max="300" step="0.5" value={draft.totalPoints[player]??''} onChange={e=>setDraft({...draft,totalPoints:{...draft.totalPoints,[player]:e.target.value===''?null:Number(e.target.value)}})}/><small>Combined points in {draft.games.at(-1)?.matchup||'the last game'}.</small></label></div>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button" onClick={()=>setOpen(false)} disabled={busy}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Saving…':'Save my picks'}</button></div></form></DialogContent></Dialog>
}
export function WeekEditor({week,save}:{week:Week;save:(w:Week,kind:'week'|'picks')=>Promise<void>}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(week),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 function gameChange(id:string,patch:Partial<Game>){setDraft(d=>({...d,games:d.games.map(g=>g.id===id?{...g,...patch}:g)}))}
 return <Dialog open={open} onOpenChange={v=>{if(busy)return;setOpen(v);if(v){setDraft(structuredClone(week));setError('')}}}><DialogTrigger asChild><button className="button">Manage week</button></DialogTrigger><DialogContent className="editor-dialog wide"><DialogHeader><DialogTitle>Manage Week {week.number}</DialogTitle><DialogDescription>Enter spread winners and final scores. Review picks, set the deadline, and record earnings.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await save(draft,'week');setOpen(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="form-scroll">
 <div className="form-grid"><label className="field">Picks close (Central time)<input type="datetime-local" required value={draft.deadlineLocal||''} onChange={e=>setDraft({...draft,deadlineLocal:e.target.value})}/></label><label className="field">Week access<Choice label="Week access" value={draft.locked?'locked':'open'} options={opts(['open','locked'])} onChange={v=>setDraft({...draft,locked:v==='locked'})}/><small>A passed deadline always closes player editing.</small></label></div>
 {draft.games.map((g,i)=><section className="game-editor" key={g.id}><div className="game-editor-heading"><strong>Game {i+1}{i===draft.games.length-1?' · Tiebreaker game':''}</strong></div><div className="form-grid"><label className="field">Matchup and spread<input required value={g.matchup} onChange={e=>gameChange(g.id,{matchup:e.target.value})}/></label><label className="field">Final score<input value={g.score} placeholder="Texans 24 – Colts 20" onChange={e=>gameChange(g.id,{score:e.target.value})}/></label><label className="field">Away team<input required value={g.teams[0]} onChange={e=>gameChange(g.id,{teams:[e.target.value,g.teams[1]]})}/></label><label className="field">Home team<input required value={g.teams[1]} onChange={e=>gameChange(g.id,{teams:[g.teams[0],e.target.value]})}/></label><label className="field">Winner against the spread<Choice label={'Result for '+g.matchup} value={g.winner} options={opts([...g.teams.filter(Boolean),'Push'])} onChange={v=>gameChange(g.id,{winner:v})}/></label></div><div className="four-fields">{players.map(p=><label className="field" key={p}>{p}<Choice label={p+' pick for '+g.matchup} value={g.picks[p]} options={opts([...new Set([...g.teams.filter(Boolean),...(g.picks[p]&&!g.teams.includes(g.picks[p])?[g.picks[p]]:[])])])} onChange={v=>gameChange(g.id,{picks:{...g.picks,[p]:v}})}/></label>)}</div></section>)}
 <button type="button" className="button" onClick={()=>setDraft({...draft,games:[...draft.games,{id:crypto.randomUUID(),matchup:'',teams:['',''],picks:{Bryan:'',Ed:'',Mike:'',Kevin:''},winner:'',score:'',kickoff:''}]})}>+ Add game</button>
 <h3>Tiebreaker · last game</h3><div className="four-fields">{players.map(p=><label className="field" key={p}>{p} prediction<input type="number" min="0" max="300" step="0.5" value={draft.totalPoints[p]??''} onChange={e=>setDraft({...draft,totalPoints:{...draft.totalPoints,[p]:e.target.value===''?null:Number(e.target.value)}})}/></label>)}</div><label className="field">Actual combined total<input type="number" min="0" max="300" step="1" value={draft.actualTotal??''} onChange={e=>setDraft({...draft,actualTotal:e.target.value===''?null:Number(e.target.value)})}/><small>Use the last game’s combined final score. Closest prediction wins a tie.</small></label>
 <h3>Weekly earnings</h3><div className="form-grid"><label className="field">Recorded winner<Choice label="Recorded weekly winner" value={draft.winner} options={opts(players)} onChange={v=>setDraft({...draft,winner:v})}/></label><label className="field">Payout ($)<input type="number" min="0" max="10000" step=".01" value={draft.earnings} onChange={e=>setDraft({...draft,earnings:Number(e.target.value)})}/></label></div><label className="field">Note<input value={draft.note} maxLength={500} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><h3>Scheduled dues</h3><div className="four-fields">{players.map(p=><label className="field" key={p}>{p} ($)<input type="number" min="0" max="10000" step=".01" value={draft.dues[p]} onChange={e=>setDraft({...draft,dues:{...draft.dues,[p]:Number(e.target.value)}})}/></label>)}</div><h3>Team earnings</h3><div className="form-grid">{['Young Guns','Old Farts'].map(t=><label className="field" key={t}>{t} ($)<input type="number" min="0" max="10000" step=".01" value={draft.teamEarnings[t]||0} onChange={e=>setDraft({...draft,teamEarnings:{...draft.teamEarnings,[t]:Number(e.target.value)}})}/></label>)}</div>
 </div>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Saving…':'Save week'}</button></div></form></DialogContent></Dialog>
}
