'use client';
import {useState} from 'react';
import {Mail,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import type {Player} from '@/lib/pool';
type Preview={report:{subject:string;html:string};recipients:{player:Player;email:string;available:boolean}[];version:string;configured:boolean};
export default function EmailReport({week,available}:{week:number;available:boolean}){
 const [open,setOpen]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[selected,setSelected]=useState<Player[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');setPreview(null);try{const r=await fetch(`/api/weekly-report?week=${week}`,{cache:'no-store'}),d=await r.json() as Preview & {error:string};if(!r.ok)throw new Error(d.error);setPreview(d)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 return <><button className="button" disabled={!available} title={available?'Preview and email this week’s newsletter':'Available after all players submit and matchups are present'} onClick={()=>{setSelected([]);setOpen(true);void load()}}><Mail size={16}/> Email weekly results</button><Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value)}}><DialogContent className="newsletter-dialog" showCloseButton={!busy} onEscapeKeyDown={e=>{if(busy)e.preventDefault()}} onPointerDownOutside={e=>{if(busy)e.preventDefault()}}><DialogTitle>Send the Week {week} newsletter</DialogTitle><DialogDescription>Choose the players who should receive this report, then select Submit. Recipient addresses stay private. Reports are sent from your Gmail account.</DialogDescription>{loading&&<p role="status">Preparing the latest saved results…</p>}{error&&<p className="error" role="alert">{error}</p>}{!loading&&<button className="text-button newsletter-reload" disabled={busy} onClick={()=>void load()}><RefreshCw size={13}/> Reload preview</button>}{preview&&<form onSubmit={async e=>{e.preventDefault();if(busy||!selected.length)return;setBusy(true);setError('');try{const r=await fetch('/api/weekly-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({week,recipients:selected,version:preview.version})}),d=await r.json() as {error:string;recipients:Player[];sent?:Player[];failed?:Player[]};if(!r.ok){if(d.failed)setSelected(d.failed);throw new Error(d.error)};setOpen(false);toast.success(`Newsletter accepted for delivery to ${d.recipients.join(', ')}.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
 <div className="newsletter-layout"><div className="newsletter-controls"><fieldset disabled={busy}><legend>Distribution list</legend>{preview.recipients.map(r=><label className="newsletter-recipient" key={r.player}><input type="checkbox" disabled={!r.available} checked={selected.includes(r.player)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,r.player]:prev.filter(p=>p!==r.player))}/><span><strong>{r.player}{r.player==='Kevin'?' · Administrator':''}</strong><small>{r.email||'No email address saved'}</small>{!r.available&&<small>Update this player in Administration.</small>}</span></label>)}</fieldset><p className="help-text">{selected.length} of 4 selected</p>{!preview.configured&&<p className="notice">Gmail needs an app password configured before sending. You can review the newsletter now.</p>}<p className="help-text">The report uses saved results. Reload the preview after making corrections.</p><div className="newsletter-buttons"><button className="button primary" type="submit" disabled={busy||!preview.configured||!selected.length}>{busy?'Sending…':'Submit'}</button><button type="button" className="button" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button></div><p className="help-text">After Submit, you’ll return to this week’s picks.</p></div><div className="newsletter-preview"><p className="newsletter-subject"><b>Subject:</b> {preview.report.subject}</p><iframe title={`Week ${week} email newsletter preview`} sandbox="" srcDoc={preview.report.html.replace(/src="https?:\/\/[^"/]+\/newsletter\//g, 'src="/newsletter/')}/></div></div>
 </form>}</DialogContent></Dialog></>;
}
