'use client';
import InviteButton from './invite-button';
import {useState,useEffect,useCallback} from 'react';
import {Trophy,ArrowUpRight,Flag,Wallet,Download,RefreshCw,LockKeyhole,CheckCircle2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Pool,Week,Player,standings,correct,players,issues,weeklyLeaders} from '@/lib/pool';
import {revealed,submissions} from '@/lib/submissions';
import {isClosed,deadlineLabel} from '@/lib/deadline';
import {PicksEditor,WeekEditor} from './editors';
type Access={admin:boolean;player:Player|null;email:string};
export default function PoolApp({initial}:{initial:Pool}){
 const [pool,setPool]=useState(initial),[weekNo,setWeekNo]=useState('3'),[tab,setTab]=useState('picks'),[access,setAccess]=useState<Access|null>(null),[revisions,setRevisions]=useState<Record<number,number>>({}),[status,setStatus]=useState('Loading saved pool…'),[loading,setLoading]=useState(false),[members,setMembers]=useState<Record<string,string>>({}),[memberBusy,setMemberBusy]=useState(''),[memberError,setMemberError]=useState('');
 const refresh=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/pool',{cache:'no-store'}),d=await r.json() as {error:string;pool:Pool;revisions:Record<number,number>;access:Access};if(!r.ok){setStatus(d.error);return}setPool(d.pool);setRevisions(d.revisions);setAccess(d.access);setStatus('Saved pool');if(d.access.admin){const m=await fetch('/api/admin',{cache:'no-store'});if(m.ok){const v=await m.json() as {members:{player:string;email:string}[]};setMembers(Object.fromEntries(v.members.map((x:{player:string;email:string})=>[x.player,x.email])))}}}catch{setStatus('Unable to load saved changes. Your last loaded view is still shown.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'view_pool_week',description:'Show a week of football pool picks without changing any saved records.',inputSchema:{type:'object',properties:{week:{type:'integer',minimum:1,maximum:18}},required:['week'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const n=(input as {week?:number})?.week;if(!Number.isInteger(n)||n!<1||n!>18)throw new Error('Week must be 1 through 18.');setWeekNo(String(n));setTab('picks');return {week:n,view:'picks'}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 const week=pool.weeks[Number(weekNo)-1],ranks=standings(pool),problems=issues(pool),leaders=week.hiddenPlayers?.length?[]:weeklyLeaders(week),closed=isClosed(week)||revealed(week),submittedCount=players.filter(p=>submissions(week)[p]).length;
 const save=async(w:Week,kind:'week'|'picks',submit=false)=>{const body=kind==='week'?{week:w,revision:revisions[w.number]}:{week:w.number,revision:revisions[w.number],submit,picks:Object.fromEntries(w.games.map(g=>[g.id,g.picks[access!.player!]])),totalPoints:w.totalPoints[access!.player!]};const r=await fetch(kind==='week'?'/api/admin':'/api/picks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string;revision:number};if(!r.ok)throw new Error(d.error||'Unable to save.');setPool(prev=>({...prev,weeks:prev.weeks.map(x=>x.number===w.number?w:x)}));setRevisions(prev=>({...prev,[w.number]:d.revision}));toast.success(kind==='week'?'Week saved':submit?'Your picks are submitted':'Draft saved; not submitted');await refresh()};
 function exportPool(){const blob=new Blob([JSON.stringify(pool,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='collins-phillips-bowl-2026-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <div className="app-shell"><Toaster/><header className="masthead"><a href="/" className="brand"><span className="brand-mark">CP<span>26</span></span><span>COLLINS PHILLIPS<span className="brand-sub">THE FOOTBALL POOL</span></span></a><div className="header-right"><nav className="site-nav" aria-label="Main navigation"><a href="/" aria-current="page">Current season</a><a href="/history">History</a></nav><div className="season-label">2026 / 2027<span>REGULAR SEASON</span></div>{access?<span className="account">{access.player||'Viewer'}{access.admin?' · Administrator':''}</span>:<a className="signin" href="/signin" target="_top">Sign in</a>}</div></header><main>
 <div className="page-heading"><div><p className="eyebrow">THE SEASON SO FAR</p><h1>Every pick counts.</h1></div><div className="heading-actions"><span className="source-label">{access?status:'Pool preview'}</span><button aria-label="Refresh pool" className="icon-button" disabled={loading} onClick={refresh}><RefreshCw size={17}/></button><button className="button" onClick={exportPool}><Download size={15}/> Export visible data</button></div></div>
 {!access&&<div className="notice"><LockKeyhole size={17}/><span>{status} Sign in to see your own private picks. Unsubmitted picks stay hidden.</span></div>}
 <div className="overview"><section className="leader-card"><div className="card-kicker"><Trophy size={18}/> SEASON LEADER</div><div className="leader-name">{ranks[0].name}<ArrowUpRight size={38}/></div><div className="leader-bottom"><strong>{ranks[0].correct}<span>correct picks</span></strong><strong>{ranks[0].wins}<span>weekly wins</span></strong><strong>${ranks[0].earnings}<span>earnings</span></strong></div></section><section className="stat-card"><Flag size={23}/><p>On the board</p><strong>Week {weekNo.padStart(2,'0')}</strong><span>{week.games.filter(g=>g.winner).length} of {week.games.length} results entered</span></section><section className="stat-card"><Wallet size={23}/><p>Weekly pool</p><strong>${players.reduce((s,p)=>s+week.dues[p],0)}</strong><span>{players.length} players · scheduled dues</span></section></div>
 <Tabs value={tab} onValueChange={setTab}><div className="tab-bar"><TabsList variant="line"><TabsTrigger value="picks">Weekly picks</TabsTrigger><TabsTrigger value="standings">Standings</TabsTrigger><TabsTrigger value="earnings">Earnings</TabsTrigger><TabsTrigger value="season">Season</TabsTrigger>{access?.admin&&<TabsTrigger value="admin">Administration</TabsTrigger>}</TabsList><Select value={weekNo} onValueChange={setWeekNo}><SelectTrigger aria-label="Select week"><SelectValue/></SelectTrigger><SelectContent>{pool.weeks.map(w=><SelectItem key={w.number} value={String(w.number)}>Week {w.number}</SelectItem>)}</SelectContent></Select></div>
 <TabsContent value="picks"><div className="section-heading"><div><h2>Week {weekNo} pick sheet</h2><p>Against the spread · {closed?'Picks closed':'Closes '+deadlineLabel(week.deadlineLocal)}</p></div><div className="actions">{access?.admin&&<WeekEditor week={week} save={save}/>} {access?.player&&!closed&&week.games.length>0&&<PicksEditor week={week} player={access.player} save={save}/>}</div></div>
 {week.number>2&&<div className="notice"><LockKeyhole size={17}/><span><strong>{submittedCount} of 4 players submitted.</strong> {revealed(week)?'All picks are visible. Only the administrator can make changes.':isClosed(week)?'The deadline has passed. Picks remain private until all four submissions.':'Picks and total-points predictions remain private until all four players submit.'}<small style={{display:'block',marginTop:5}}>{players.map(p=>p+': '+(submissions(week)[p]?'Submitted':'Not submitted')).join(' · ')}</small></span></div>}
 {week.winner&&<div className="winner-strip"><Trophy size={17}/><strong>{week.winner} won Week {week.number}</strong><span>${week.earnings} recorded payout{week.note?' · '+week.note:''}</span></div>}
 {!week.games.length?<div className="empty-state"><Flag size={30}/><h3>No matchups yet</h3><p>The administrator can add games and spreads for Week {week.number}.</p>{pool.finalSchedules[weekNo]&&<p>A draft schedule is available in the Season tab.</p>}</div>:<div className="table-panel"><Table><TableHeader><TableRow><TableHead className="matchup-cell">MATCHUP / LINE</TableHead>{players.map(p=><TableHead key={p}>{p.toUpperCase()}</TableHead>)}<TableHead>SPREAD RESULT</TableHead></TableRow></TableHeader><TableBody>{week.games.map((g,i)=><TableRow key={g.id}><TableCell><div className="matchup"><span className="game-number">{String(i+1).padStart(2,'0')}</span><div><strong>{g.matchup}</strong>{i===week.games.length-1&&<small className="tie-label">TOTAL-POINTS TIEBREAKER</small>}</div></div></TableCell>{players.map(p=><TableCell key={p}><span className={g.winner&&g.winner===g.picks[p]?'pick won':g.picks[p]&&!g.teams.includes(g.picks[p])?'pick review':'pick'}>{week.hiddenPlayers?.includes(p)?'Private':g.picks[p]||'—'}</span>{g.picks[p]&&!g.teams.includes(g.picks[p])&&<small>Review spelling</small>}</TableCell>)}<TableCell><span className={g.winner?'result final':'result'}>{g.winner||'Awaiting result'}</span>{g.score&&<small>{g.score}</small>}</TableCell></TableRow>)}<TableRow className="total-row"><TableCell>Correct picks</TableCell>{players.map(p=><TableCell key={p}>{week.hiddenPlayers?.includes(p)?'Private':correct(week,p)}</TableCell>)}<TableCell>{week.games.filter(g=>g.winner==='Push').length} pushes</TableCell></TableRow><TableRow><TableCell>Total points prediction</TableCell>{players.map(p=><TableCell key={p}>{week.hiddenPlayers?.includes(p)?'Private':week.totalPoints[p]??'—'}</TableCell>)}<TableCell>Actual: {week.actualTotal??'—'}</TableCell></TableRow></TableBody></Table></div>}
 <div className="under-table"><span>1 point per correct spread pick. Pushes earn 0, matching the workbook.</span><span>{leaders.length===1?'Calculated weekly winner: '+leaders[0]:leaders.length>1?'Still tied: '+leaders.join(', '):week.hiddenPlayers?.length?'Weekly winner stays private until all four submit.':'Weekly winner pending remaining results.'}</span></div>
 </TabsContent>
 <TabsContent value="standings"><div className="section-heading"><h2>Season standings</h2><span>Revealed weeks only · ranked by correct picks</span></div><div className="table-panel"><Table><TableHeader><TableRow>{['RANK','PLAYER','CORRECT','WEEKLY WINS','EARNINGS'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{ranks.map(p=><TableRow key={p.name}><TableCell><span className="rank">{1+ranks.filter(r=>r.correct>p.correct).length}</span></TableCell><TableCell><strong>{p.name}</strong><small>{p.name==='Kevin'||p.name==='Mike'?'Young Guns':'Old Farts'}</small></TableCell><TableCell className="big-number">{p.correct}</TableCell><TableCell>{p.wins}</TableCell><TableCell>${p.earnings}</TableCell></TableRow>)}</TableBody></Table></div><div className="team-grid">{Object.entries(pool.teams).map(([name,members])=><section key={name} className="team-card"><p className="eyebrow">{members.join(' + ')}</p><h2>{name}</h2><div><strong>{pool.weeks.reduce((s,w)=>s+(w.hiddenPlayers?.length?0:members.reduce((n,p)=>n+correct(w,p),0)),0)}</strong><span>correct picks</span><strong>${pool.weeks.reduce((s,w)=>s+(w.teamEarnings[name]||0),0)}</strong><span>recorded team earnings</span></div></section>)}</div><p className="help-text">Blank future weeks do not count toward standings. Original pick spellings are retained until the administrator corrects them.</p></TabsContent>
 <TabsContent value="earnings"><div className="section-heading"><div><h2>Season ledger</h2><p>Scheduled dues and recorded payouts. These amounts do not indicate payment received.</p></div>{access?.admin&&<WeekEditor week={week} save={save}/>}</div><div className="ledger-cards">{ranks.map(p=><section className="ledger-card" key={p.name}><h3>{p.name}</h3><strong>${p.dues-p.earnings}</strong><span>season dues less earnings</span><small>${p.dues} dues · ${p.earnings} won</small></section>)}</div><div className="table-panel"><Table><TableHeader><TableRow><TableHead>WEEK</TableHead><TableHead>WINNER</TableHead><TableHead>PAYOUT</TableHead><TableHead>POOL DUES</TableHead><TableHead>NOTE</TableHead></TableRow></TableHeader><TableBody>{pool.weeks.map(w=><TableRow key={w.number}><TableCell>Week {w.number}</TableCell><TableCell>{w.winner||'Pending'}</TableCell><TableCell>{w.winner?'$'+w.earnings:'—'}</TableCell><TableCell>${players.reduce((s,p)=>s+w.dues[p],0)}</TableCell><TableCell>{w.note||'—'}</TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
 <TabsContent value="season"><div className="section-heading"><h2>The 18-week season</h2><span>{pool.season}</span></div><div className="season-grid">{pool.weeks.map(w=><button key={w.number} className={'week-card '+(w.number===Number(weekNo)?'selected':'')} onClick={()=>{setWeekNo(String(w.number));setTab('picks')}}><span>WEEK {String(w.number).padStart(2,'0')}</span><strong>{w.winner?w.winner+' wins':w.games.length?w.games.length+' matchups':'Not scheduled'}</strong><small>{w.games.length?w.games.filter(g=>g.winner).length+' results entered':'Add matchups when ready'}</small></button>)}</div><div className="section-heading"><div><h2>Late-season draft schedules</h2><p>Imported from “Final Schedules”; confirm matchups and add spreads before opening picks.</p></div></div><div className="schedule-grid">{Object.entries(pool.finalSchedules).map(([n,games])=><section className="schedule-card" key={n}><h3>Week {n}</h3><ol>{games.map((g,i)=><li key={i}>{g}</li>)}</ol></section>)}</div></TabsContent>
 {access?.admin&&<TabsContent value="admin"><div className="section-heading"><div><h2>Pool administration</h2><p>You control player access, results, corrections, and all earnings.</p></div><WeekEditor week={week} save={save}/></div><section className="settings-panel"><h3>Player sign-in emails</h3><p>Assign each player’s email, then create a private setup link to share with them. Creating a new link lets them reset their password.</p><div className="member-grid">{players.map(p=><form key={p} onSubmit={async e=>{e.preventDefault();setMemberBusy(p);setMemberError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'member',player:p,email:members[p]})}),d=await r.json() as {error:string};if(!r.ok)throw new Error(d.error);toast.success(p+'’s access saved')}catch(e){setMemberError((e as Error).message)}finally{setMemberBusy('')}}}><label className="field">{p}<input type="email" required value={members[p]||''} placeholder="Player’s email" onChange={e=>setMembers({...members,[p]:e.target.value})}/></label><button className="button" disabled={!!memberBusy}>{memberBusy===p?'Saving…':'Save access'}</button><InviteButton player={p} email={members[p]||''}/></form>)}</div>{memberError&&<p className="error" role="alert">{memberError}</p>}</section><section className="settings-panel"><h3>Import review</h3><p>Week 1 has one missing result (Broncos @ Chiefs). The workbook’s recorded winner remains Mike. Blank future-week totals of 20 were excluded.</p>{problems.length?<ul className="issue-list">{problems.map(x=><li key={x.game+x.player}><span>Week {x.week} · {x.player}: <strong>{x.value}</strong><small>{x.matchup}</small></span><button className="button" onClick={()=>{setWeekNo(String(x.week));setTab('picks')}}>Review week</button></li>)}</ul>:<p><CheckCircle2 size={16}/> No unmatched team names.</p>}<p className="help-text">Correct spelling in Manage week to update scores. Historical payouts change only when you edit them.</p></section></TabsContent>}
 </Tabs><footer><span>COLLINS PHILLIPS BOWL</span><span>Imported from {pool.source}</span>{access&&<button className="text-button" onClick={async()=>{await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});window.location.assign('/')}}>Sign out</button>}</footer></main></div>;
}